### ISSUE TITLE
OnSplitSliderChanged MethodAccessExeption

### ISSUE THREAD

**Issue by DarthMullins** [paddywaan/PaddysVHMods#1]
I keep getting this error logged in the BepinEX error log. I dont see any ingame issues that I am aware of. Just wanted to share in case it might be causing issues I am not aware of.

Error Log Excerpt
> [Error  : Unity Log] MethodAccessException: Method `InventoryGui.OnSplitSliderChanged(single)' is inaccessible from method `PaddysMods.Hooks.InventoryGui_Update(On.InventoryGui/orig_Update,InventoryGui)'
>Stack trace:
>PaddysMods.Hooks.InventoryGui_Update (On.InventoryGui+orig_Update orig, InventoryGui self) (at <bc6dd255ee91484b912ab5fe133da7bb>:0)
>(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<InventoryGui::Update>?572587904(InventoryGui)

>[Error  : Unity Log] MethodAccessException: Method `InventoryGui.OnSplitSliderChanged(single)' is inaccessible from method `PaddysMods.Hooks.InventoryGui_Update(On.InventoryGui/orig_Update,InventoryGui)'
>Stack trace:
>PaddysMods.Hooks.InventoryGui_Update (On.InventoryGui+orig_Update orig, InventoryGui self) (at <bc6dd255ee91484b912ab5fe133da7bb>:0)
>(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<InventoryGui::Update>?572587904(InventoryGui)

Please let me know if I can provide any other information.

**Comment by paddywaan** [comment]
I've seen this error once before when a user was attempting to use a previous/outdated version of the game. Is this also the case for you? if so try removing hookgen and grab the deprecated mmhook package alongside the first release of this mod, and it "might" work.

**Comment by DarthMullins** [comment]
Thanks for the follow-up.
I am currently running:
>Game Version: 0.147.3
BepInEx version 5.4.8.0
HookGenPatcher Version 0.0.2

I have also deleted the MMHOOK folder under `Valheim\BepInEx\Plugins` to have it regenerated since updating HookGenPatcher to 0.0.2

The error seems to occur around the time I am building something.
I have attached my BepInEx Output Log if that is any help.
[LogOutput.log](https://github.com/paddywaan/PaddysVHMods/files/6118131/LogOutput.log)

**Comment by paddywaan** [comment]
From the sheer quantity of mods you are using i'd say there is a fair chance of conflict between this function and another mods implementation of my slider keypad shortcuts for stacks. I'm not going to crosscheck compatibility for : `[Info   :   BepInEx] 57 plugins to load`, so unfortunately I'd need to know specifically which two mods are causing this conflict in order to resolve this issue. I am unable to replicate your issue with both versions listed under thundstore releases on a fresh install.

**Comment by DarthMullins** [comment]
Ok, again, mainly just wanted to share the error I am getting on my end. I am not seeing anything noticeable breaking in-game. I will follow up if I have any more information for you.
Feel free to close this tracker if you want.

**Comment by DarthMullins** [comment]
Following up, I tried removing all other mods, and reinstalling the game with Bepin and HookGenPatcher. I am still getting the error. It shows up any time I equip an item using the 8 numbered quick slots. If I equip items by opening the inventory and right clicking I do not get the error.
I still haven't seen any issues resulting from the error in game.
[LogOutput-2021-03-11.log](https://github.com/paddywaan/PaddysVHMods/files/6125938/LogOutput-2021-03-11.log)

**Comment by paddywaan** [comment]
Okay, so using HookGenPatcher 0.0.2 and paddysmods 1.0.2 i've reproduced the error as you described. Not entirely sure what happened here but I guess the hook that 1.0.2 was compiled using has had its method signature changed, not really sure what else would cause this as this appears to be working fine in my dev builds. Keep an eye out for a new version Soon™
