### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by skarchbr** [paddywaan/PaddysVHMods#4]
This is the error I'm getting and I can't find any cfg in the config folder of BelpInEx. 

[Error  :   BepInEx] Could not load [SkillfulProgression 1.0.1] because it has missing dependencies: Paddy_StackingNotifications

**Comment by paddywaan** [comment]
Please acquire the missing dependency, which the mod links too on thunderstore:
![image](https://user-images.githubusercontent.com/70168382/114261913-e9d37d00-99d4-11eb-89ae-600e23cdd377.png)

**Comment by skarchbr** [comment]
I did this already, but I'm not getting any config file on the BelpInEx/config folder. Where the config file should be?

**Comment by paddywaan** [comment]
There is no config file for this mod, yet.

**Comment by skarchbr** [comment]
Ok. But in how much does it increases the XP gain by skill?

**Comment by paddywaan** [comment]
It is purely dependant upon damage (and hence items, and progression, as well as enemy total HP). It depends precisely but usually it maxes out at around 5-10XP for the more rare events/circumstances. The battleaxe tends to be a bit of an exception as the condition is so precise and hard to achieve, but theoretically it could be upwards of 30 (however i'd be surprised if anyone actually manages to pull this off.)

I was thinking about exposing configs to allow tweaking of xp multipliers per skill but haven't got around to it yet. Honestly i just kind of tweaked the balance until i achieved something which felt rewarding for achieving the more skillful parts of combat and left it at that. If you have any specific ideas please feel free to create a feature request detailing as such.

**Comment by skarchbr** [comment]
Oh thats great. Thank you very much ^.^
I saw this somewhere but one good thing to add is XP based on specialist of the weapon. Example: More XP to Bows if hit an target as far as possible, sneaking attack with Knifes etc. Stuffs like this. maybe an option to add the XP for EACH weapon as well should be good cause configure XP by XP is nice. Idk. If I have any more ideas I'll let you know

**Comment by paddywaan** [comment]
I mean, all of that is already implemented.. that is kinda what the intention of this mod was. But yes, configs will come when i find some time to work on something that is not jotunn.
